import express from 'express';
import account from './account';
import ads from './ads/adsRouter';
import bankRouter from './bank/bankRouter';
import businessinfo from './businessInfo';
import card from './cards/cardRouter';
import categoryRouter from './category/categoryRouter';
import clients from './clients/clientsRouter';
import comments from './comments/commentrouter';
import contact from './contacts/contactrouter';
import eventPaymentMethod from './events/eventPaymentMethodRouter';
import eventPayment from './events/eventPaymentRouter';
import event from './events/eventRouters';
import eventSittingPlace from './events/eventSittingPlaceRouter';
import fileRouter from './files/fileRouter';
import flutterwave from './flutterwave/flutterwave';
import guestRouter from './guests/guestRouter';
import image from './images/imagesRouter';
import notification from './notifications';
import permission from './permissions/permissionRoutes';
import representative from './representative';
import rolePerm from './rolepermissions/rolepermissions';
import role from './roles/roleRoutes';
import ticket from './tickets/ticketRouter';
import transactions from './transactions/transactionRouter';
import user from './users/userRoutes';

const router = express.Router();
router.use('/users', user);
router.use('/permissions', permission);
router.use('/roles', role);
router.use('/rolesPermissions', rolePerm);
router.use('/contacts', contact);
router.use('/events', event);
router.use('/events/eventPayment', eventPayment);
router.use('/events/eventPaymentMethod', eventPaymentMethod);
router.use('/events/eventSittingPlaces', eventSittingPlace);
router.use('/events/tickets', ticket);
router.use('/cards', card);
router.use('/transactions', transactions);
router.use('/comments', comments);
router.use('/notifications', notification);
router.use('/client', clients);
router.use('/image', image);
router.use('/advert', ads);
router.use('/guest', guestRouter);
router.use('/flutterwave', flutterwave);
router.use('/files', fileRouter);
router.use('/category', categoryRouter);
router.use('/bank', bankRouter);
router.use('/account', account);
router.use('/representative', representative);
router.use('/businessinfo', businessinfo);
export default router;
